name: Publish selected production build
on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - name: Setup dotnet tools
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Checkout repository
        uses: actions/checkout@master

      - name: Build project
        run: dotnet build -c Release

      - name: Push project
        run: dotnet nuget push **/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} --skip-duplicate